spring.application.name=osrs-market-tracker

# Tells Spring how the application should be configured
# Maps/Configures those values for Spring
# Database config, server settings, logging, JPA behavior etc


# ---- Database ---- #
# Spring Boot reads configuration including Spring Data JPA + PostregSQL
#
Database= osrs_market_tracker
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update